spring.application.name=cms
spring.datasource.url=jdbc:postgresql://localhost:5432/cms
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
auth.token.key=0a2079a489a5f2f10fe19ed6c7d2c7272c71635f1c16166b6cac398e0242bc5e
auth.token.expirationTIme=3600000
